---
title: "Nadeu_2022_reanalysis_cell_separation"
author: "Pakorn Sagulkoo"
format:
  html:
    embed-resources: true
editor: visual
---

## Import the relevant packages and set working path directory

```{r, setup, message=FALSE, warning=FALSE}
# Attach the packages you will need for the analysis.
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(tidyverse)
library(DT)
```

```{r}
# Check working path
getwd()
```

## Define parameters

```{r}
# Paths
path_to_obj <- here::here("reanalysis/results/R_objects/3.seurat_filtered.rds")
path_to_save_microenv <- here::here("reanalysis/results/R_objects/4.seurat_microenvironment.rds")
path_to_save_leukemic <- here::here("reanalysis/results/R_objects/4.seurat_leukemic.rds")


# Colors
color_palette <- c("black", "gray", "red", "yellow", "violet", "green4",
                   "blue", "mediumorchid2", "coral2", "blueviolet",
                   "indianred4", "deepskyblue1", "dimgray", "deeppink1",
                   "green", "lightgray", "hotpink1")


# Source functions
source(here::here("bin/utils.R"))
```

## Load data

```{r}
seurat <- readRDS(path_to_obj)
```

## Normalization, Dimensionality reduction and batch effect correction

```{r, message=FALSE, warning=FALSE}
seurat <- NormalizeData(seurat, normalization.method = "LogNormalize", scale.factor = 10000) 
seurat <- FindVariableFeatures(seurat) 
seurat <- ScaleData(seurat) 
seurat <- RunPCA(seurat) 
seurat <- RunHarmony(seurat, group.by.vars = "sample_id", dims = 1:30) 
seurat <- RunUMAP(seurat, dims = 1:30, reduction = "harmony")
```

## Visualize lineage markers

```{r, message=FALSE, warning=FALSE}
lineage_markers <- c("CD79A", "CD3D", "CD8A", "IL7R", "NKG7",
                     "LYZ", "HBA1", "TOP2A")
lineage_markers_ggs <- purrr::map(lineage_markers, function(x) {
  p <- FeaturePlot(seurat, features = x, pt.size = 0.45)
  p +
    scale_color_viridis_c(option = "magma")
})
names(lineage_markers_ggs) <- lineage_markers
lineage_markers_ggs
```

## Cluster

```{r, message=FALSE, warning=FALSE}
seurat <- FindNeighbors(
  seurat,
  dims = 1:30,
  reduction = "harmony"
)
seurat <- FindClusters(seurat, resolution = 0.1)
DimPlot(seurat, cols = color_palette, pt.size = 0.3)
richter_levels <- c("richter_sp", "richter_while-ibrutinib",
                    "richter_post-ofatu-duvelisib")
seurat$is_richter <- ifelse(
  seurat$sample_description %in% richter_levels,
  TRUE,
  FALSE
)
DimPlot(seurat, group.by = "is_richter")
DimPlot(seurat, group.by = "tissue")
```

### Erythriblast cluster and filter it out

```{r}
# Subcluster
seurat <- FindSubCluster(
  seurat,
  cluster = "4",
  graph.name = "RNA_snn",
  subcluster.name = "fetch_erythroblasts",
  resolution = 0.2
)
DimPlot(seurat, group.by = "fetch_erythroblasts", cols = color_palette)
```

```{r}
Idents(seurat) <- "fetch_erythroblasts"
seurat <- JoinLayers(seurat)

# Find markers of potential erythroblasts
markers_erythroblasts <- purrr::map(c("4_1", "4_3"), function(x) {
  df <- FindMarkers(
    seurat,
    ident.1 = x,
    only.pos = TRUE,
    logfc.threshold = 0.75
  )
  df <- df %>%
    rownames_to_column("gene") %>%
    arrange(desc(avg_log2FC))
  df
})
names(markers_erythroblasts) <- c("4_1", "4_3")
DT::datatable(markers_erythroblasts$`4_1`)
DT::datatable(markers_erythroblasts$`4_3`)
```

```{r}
# Subset
mask <- colnames(seurat)[!(seurat$fetch_erythroblasts %in% c("4_1", "4_3"))]
seurat <- subset(seurat, cells = mask)
DimPlot(seurat, cols = color_palette)
```

## Separate CD5+ B cells from microenvironment

```{r}
microenv_clusters <- c("2", "5")
leuk_clusters <- c("0", "1", "3", "4_0", "4_2", "6")
microenv <- subset(seurat, idents = microenv_clusters)
leuk <- subset(seurat, idents = leuk_clusters)
DimPlot(leuk, cols = color_palette, pt.size = 0.3)
DimPlot(microenv, cols = color_palette, pt.size = 0.3)
```

## Save the objects

```{r}
saveRDS(microenv, path_to_save_microenv)
saveRDS(leuk, path_to_save_leukemic)
```


