---
title: "Nadeu_2022_gene_expression_analysis"
author: "Pakorn Sagulkoo"
format:
  html:
    embed-resources: true
editor: visual
---

## Import the relevant packages and set working path directory

```{r, setup, message=FALSE, warning=FALSE}
# Attach the packages you will need for the analysis.
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(UpSetR)
library(ggrepel)
library(ggforce)
library(tidyverse)
```

```{r}
# Check working path
getwd()
```

## Define parameters

```{r}
# Paths
path_to_12 <- here::here("reanalysis/results/R_objects/6.seurat_annotated_12.rds")
path_to_19 <- here::here("reanalysis/results/R_objects/6.seurat_annotated_19.rds")
path_to_63 <- here::here("reanalysis/results/R_objects/patient_63/3.seurat_annotated.rds")
path_to_365 <- here::here("reanalysis/results/R_objects/6.seurat_annotated_365.rds")
path_to_3299 <- here::here("reanalysis/results/R_objects/6.seurat_annotated_3299.rds")
path_to_save_rds <- here::here("reanalysis/results/4_differential_expression/tmp/patient_specific_differential_expression_analysis_rt_vs_cll.rds")
path_to_save_xlsx <- here::here("reanalysis/results/tables/DEA/patient_specific_differential_expression_analysis_rt_vs_cll.xlsx")

# Colors
color_palette <- c("black", "gray", "red", "yellow", "violet", "green4",
                   "blue", "mediumorchid2", "coral2", "blueviolet",
                   "indianred4", "deepskyblue1", "dimgray", "deeppink1",
                   "green", "lightgray", "hotpink1")


# Source functions
source(here::here("bin/utils.R"))

# Thresholds
alpha <- 0.05
min_avg_log2FC <- 0.25
selected_avg_log2FC_l <- c(
  "12" = 1.25,
  "19" = 0.75,
  "3299" = 0.75,
  "365" = 1.5,
  "63" = 1.25  
)
selected_avg_log2FC <- 1.25
selected_pct_cells <- 10
selected_significance_alpha <- alpha
```

## Load data

```{r}
paths_to_load <- c(
  "12" = path_to_12,
  "19" = path_to_19,
  "63" = path_to_63,
  "365" = path_to_365,
  "3299" = path_to_3299
)
seurat_list <- purrr::map(paths_to_load, readRDS)
seurat_list
```

```{r}
# Plot
umaps_annotations <- purrr::map(names(seurat_list), function(x) {
  p <- plot_annotation(
    seurat_list[[x]],
    pt_size = 0.5,
    colors_reference = color_annotations,
    patient_id = x
  )
  p +
    ggtitle(x) +
    theme(plot.title = element_text(size = 12, face = "bold", hjust = 0.5))
})

umaps_annotations
```

## Differential expression analysis

```{r}
comparisons <- list(
  "12" = list(
    richter = c("CCND2lo RT", "CCND2hi RT"),
    cll = c("CXCR4hiCD27lo", "CXCR4loCD27hi", "MIR155HGhi", "MZB1hiIGHMhiXBP1hi")
  ),
  "19" = list(
    richter = c("MIR155HGhi RT", "TP53INP1hi RT"),
    cll = c("CXCR4hiCD27lo", "CXCR4loCD27hi", "MIR155HGhi CLL")
  ),
  "63" = list(
    richter = "RT quiescent",
    cll = "CLL"
  ),
  "365" = list(
    richter = c("RT quiescent", "CXCR4loCD27hi RT", "MIR155HGhi RT"),
    cll = c("CLL")
  ),
  "3299" = list(
    richter = "RT",
    cll = c("CXCR4hiCD27lo", "CXCR4loCD27hi", "CD83loMIR155HGhi", "CD83hiMIR155HGhi")
  )
)

dea <- purrr::map(names(comparisons), function(x) {
  print(x)
  seurat_obj <- seurat_list[[x]]
  Idents(seurat_obj) <- "annotation_final"
  df <- FindMarkers(
    seurat_obj,
    ident.1 = comparisons[[x]][["richter"]],
    ident.2 = comparisons[[x]][["cll"]],
    only.pos = FALSE,
    logfc.threshold = 0
  )
  df <- df %>%
    rownames_to_column("gene") %>%
    arrange(desc(avg_log2FC))
  df
}) 

names(dea) <- names(comparisons)
```

```{r, warning=FALSE, message=FALSE}
dea <- purrr::map(names(dea), function(x) {
  df <- dea[[x]]
  df$direction <- case_when(
    df$p_val_adj < alpha & df$avg_log2FC > min_avg_log2FC ~ "up",
    df$p_val_adj < alpha & df$avg_log2FC < 0 & abs(df$avg_log2FC) > min_avg_log2FC ~ "down"
  )
  df$direction[is.na(df$direction)] <- "not sig."
  #pct_cells <- rowMeans(seurat_list[[x]][["RNA"]]@counts > 0) * 100
  pct_cells <- rowMeans(LayerData(seurat_list[[x]][["RNA"]], layer = "counts") > 0) * 100 
  df$pct_cells_expressing <- pct_cells[df$gene]
  df
})

names(dea) <- names(comparisons)
upregulated_richter <- purrr::map(dea, function(df) df$gene[df$direction == "up"])
downregulated_richter <- purrr::map(dea, function(df) df$gene[df$direction == "down"])

print("DEA patient 12")
DT::datatable(dea$`12`, options = list(scrollX = TRUE))
print("DEA patient 19")
DT::datatable(dea$`19`, options = list(scrollX = TRUE))
print("DEA patient 63")
DT::datatable(dea$`63`, options = list(scrollX = TRUE))
print("DEA patient 365")
DT::datatable(dea$`365`, options = list(scrollX = TRUE))
print("DEA patient 3299")
DT::datatable(dea$`3299`, options = list(scrollX = TRUE))
```

```{r}
# Upset plot
upset_upregulated <- upset(fromList(upregulated_richter), order.by = "freq")
upset_downregulated <- upset(fromList(downregulated_richter), order.by = "freq")
upset_upregulated
upset_downregulated
```

```{r, fig.wide=TRUE, warning=FALSE, message=FALSE}
# MA plot
ma_plots <- purrr::map(names(dea), function(x) {
  df <- dea[[x]]
  selected_avg_log2FC <- selected_avg_log2FC_l[x]
  p <- ma_plot(
    df,
    selected_avg_log2FC = selected_avg_log2FC,
    selected_pct_cells = selected_pct_cells,
    selected_significance_alpha = selected_significance_alpha
  ) +
    ggtitle(x) +
    theme(plot.title = element_text(hjust = 0.5))
  p
})
names(ma_plots) <- names(dea)
ma_plots
```

## Save

```{r, eval=FALSE}
saveRDS(dea, path_to_save_rds)
openxlsx::write.xlsx(dea, path_to_save_xlsx)
```

