---
title: "Nadeu_2022_qc_object_case63"
author: "Pakorn Sagulkoo"
format:
  html:
    embed-resources: true
editor: visual
---

## Import the relevant packages and set working path directory

```{r, setup, message=FALSE, warning=FALSE}
# Attach the packages you will need for the analysis.
library(scater)
library(Seurat)
library(ggpubr)
library(tidyverse)
library(DT)
```

```{r}
# Check working path
getwd()
```

## Parameters

```{r}
# Paths
path_to_obj <- here::here("reanalysis/results/R_objects/patient_63/1.seurat_object_unfiltered.rds")
path_to_save <- here::here("reanalysis/results/R_objects/patient_63/2.seurat_object_filtered.rds")

# Functions
source(here::here("bin/utils.R"))

# Thresholds
min_lib_size <- 150000
max_lib_size <- 700000
min_n_genes <- 550
max_n_genes <- 3750
max_pct_mt <- 18
min_cells <- 3
```

## Load data

```{r}
seurat <- readRDS(path_to_obj)
seurat
```

## Library complexity

```{r, warning=FALSE, message=FALSE}
# Calculate mean library size
seurat$time_point[is.na(seurat$time_point)] <- "empty"
seurat$sample_id[is.na(seurat$sample_id)] <- "empty"
lib_complexity_df <- seurat@meta.data %>%
  dplyr::group_by(time_point, sample_id) %>%
  dplyr::summarise(
    mean_n_features = round(mean(nFeature_RNA), 2),
    sd_n_features = round(sd(nFeature_RNA), 2)) %>%
  dplyr::arrange(time_point)
print(lib_complexity_df)

# Plot library size distribution
lib_size_per_time_point <- seurat@meta.data %>%
  ggplot(aes(time_point, nFeature_RNA, fill = tissue)) +
    geom_violin() +
    scale_y_log10() +
    labs(title = "", x = "", y = "Number of Detected Genes") +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 13),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 13),
      legend.title = element_blank()
    ) 
lib_size_per_time_point
```

It is worth noting that NA or empty values are from experiment wells which are negative constrols.

## Filter out low quality cells

```{r fig.wide=TRUE}
# Library Size
lib_size_hist <- seurat@meta.data %>%
  plot_histogram_qc(x = "nCount_RNA", x_lab = "Library Size (log10(total UMI))") +
  geom_vline(xintercept = min_lib_size, linetype = "dashed", color = "red") +
  geom_vline(xintercept = max_lib_size, linetype = "dashed", color = "red")
lib_size_hist
```

```{r fig.wide=TRUE}
# Number of detected genes
n_genes_hist <- seurat@meta.data %>%
  plot_histogram_qc(x = "nFeature_RNA", x_lab = "Number of Detected Genes") +
  geom_vline(xintercept = min_n_genes, linetype = "dashed", color = "red") +
  geom_vline(xintercept = max_n_genes, linetype = "dashed", color = "red")
n_genes_hist
```

```{r, warning=FALSE}
# Percentage of mitochondrial expression
seurat$pct_mt <- PercentageFeatureSet(seurat, pattern = "^MT-")

pct_mt_hist <- seurat@meta.data %>%
  plot_histogram_qc(x = "pct_mt", x_lab = "% Mitochondrial Expression") +
  geom_vline(xintercept = max_pct_mt, linetype = "dashed", color = "red") +
  scale_x_continuous(limits = c(0, 100))
pct_mt_hist
```

```{r}
# Percentage of ribosomal expression
seurat$pct_ribosomal <- PercentageFeatureSet(
  seurat,
  pattern = "^RPS"
)
pct_ribosomal_hist <- seurat@meta.data %>%
  plot_histogram_qc(x = "pct_ribosomal", x_lab = "% Ribosomal Expression")
pct_ribosomal_hist
```

```{r}
# Filter out low qc cells
metadata_before_qc <- seurat@meta.data
is_low_quality <- 
  seurat$nCount_RNA < min_lib_size |
  seurat$nCount_RNA > max_lib_size |
  seurat$nFeature_RNA < min_n_genes |
  seurat$nFeature_RNA > max_n_genes |
  seurat$pct_mt > max_pct_mt
table(is_low_quality)
seurat$keep_cells <- !is_low_quality
Idents(seurat) <- "keep_cells"
seurat
seurat <- subset(seurat, idents = TRUE)
seurat
metadata_after_qc <- seurat@meta.data
```

```{r, warning=FALSE, message=FALSE}
# QC summary table
qc_before <- metadata_before_qc %>%
  group_by(sample_id, time_point) %>% 
  summarise(num_cells_before_qc = n())
qc_after <- metadata_after_qc %>%
  group_by(sample_id, time_point) %>%
  summarise(
    num_cells_after_qc = n(),
    average_library_size = mean(nCount_RNA),
    average_num_detected_genes = mean(nFeature_RNA),
    average_mitochondrial_fraction = mean(pct_mt)
  )
qc_table <- left_join(qc_before, qc_after, by = "sample_id")
DT::datatable(qc_table)
```

## Filter out genes expressing in a low number of cells

```{r, fig.wide=TRUE, warning=FALSE}
# Plot the distribution of the number of cells that each gene expresses
n_cells <- Matrix::rowSums(LayerData(seurat[["RNA"]], layer = "counts") > 0)
gene_qc <- n_cells %>% 
  as.data.frame() %>% 
  ggplot(aes(n_cells)) + 
    geom_histogram(bins = 100, alpha = 0.75) +
    scale_x_log10("Number of cells") +
    theme_bw() 
gene_qc +
  geom_vline(xintercept = min_cells, linetype = "dashed", color = "red")
```

```{r, fig.height=10, fig.width=6}
# Plot genes with highest expression
top_50_genes <- sort(n_cells, decreasing = TRUE)[1:50]
top_50_genes_df <- data.frame(
  gene = names(top_50_genes),
  n_cells = top_50_genes
)
top_50_genes_df %>%
  ggplot(aes(fct_reorder(gene, n_cells), n_cells)) +
    geom_point() +
    labs(x = "", y = "Number of expressing cells") +
    coord_flip()
```

```{r, warning=FALSE, message=FALSE}
# Filter out 
kept_genes <- rownames(seurat)[n_cells > min_cells]
table(n_cells > min_cells)
seurat
seurat <- subset(seurat, features = kept_genes)
seurat
```

## Save the filtered object

```{r, eval=FALSE}
saveRDS(seurat, path_to_save)
```





